version: 1

disable_existing_loggers: True

formatters:
  complete:
    format: '[%(asctime)s] [%(process)d-%(thread)d] %(levelname)s [%(funcName)s:%(filename)s, %(lineno)d] %(message)s'
    datefmt: '%F %T'
  simple:
    # format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    format: '[%(asctime)s] %(levelname)s [%(funcName)s:%(filename)s, %(lineno)d] %(message)s'
    datefmt: '%F %T'


handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: /log/info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20 #most 20 extensions
    encoding: utf8
  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: complete
    filename: /log/errors.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
  info_file_time_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: simple
    filename: /log/info_time.log
    when: D
    backupCount: 1
    encoding: utf8
    # suffix: "%Y-%m-%d.log"

    
loggers:
  main:
    level: DEBUG
    handlers: [console,info_file_time_handler,error_file_handler]
root:
  level: DEBUG
  handlers: [console,info_file_time_handler,error_file_handler]